<<<<<<< HEAD
server.port=8091

=======
# ???????????? ???????
server.port=8091

# ???????????? ???? ??????
>>>>>>> 7c22202 (Добавлены профили для разработки и тестирования)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

<<<<<<< HEAD
=======
# ???????????? JPA
>>>>>>> 7c22202 (Добавлены профили для разработки и тестирования)
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

<<<<<<< HEAD
spring.h2.console.enabled=true

=======
# ????????? ??????? H2
spring.h2.console.enabled=true

# ????????? ???????????
>>>>>>> 7c22202 (Добавлены профили для разработки и тестирования)
logging.level.org.springframework=INFO
logging.level.org.hibernate=INFO
logging.level.org.unidata1=DEBUG
